language: go

go: 1.17.x

arch: ppc64le

dist: focal

env:
  global: BUILD_WITH_CONTAINER=0

before_install: 
  - echo "Validating istio upstream repo"
  
install:
  - sudo apt install -y make gcc


script:
  - travis_wait 30 make
  - make test

after_success:
    - echo "Completed execution"
