language: go

go: 1.17.x

arch: ppc64le

dist: focal

install:  sudo apt install -y  make wget tar git gcc make

env:
  global: BUILD_WITH_CONTAINER=0

before_install: 
  - echo "Validating istio upstream repo"
  
script: 
  - travis_wait make
  - travis_wait make test

after_success:
    - echo "Completed execution"
