language: go

go: 1.17.5

arch: ppc64le

dist: focal

env:
  global: BUILD_WITH_CONTAINER=0

before_install: 
  - echo "Validating istio upstream repo"
  
install:
   - sudo apt update
   - sudo apt install -y make gcc docker
script:
  - travis_wait 40 make
  # - travis_wait 40 make test

after_success:
    - echo "Completed execution"
